# Generated by Django 3.2 on 2021-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smile', models.CharField(max_length=50)),
                ('mol_log', models.FloatField()),
                ('tpsa', models.FloatField()),
                ('nhoh_count', models.IntegerField()),
                ('no_count', models.IntegerField()),
                ('num_ha_acceptors', models.IntegerField()),
                ('num_h_donors', models.IntegerField()),
                ('num_rotatable_bonds', models.IntegerField()),
                ('calc_num_amide_bonds', models.IntegerField()),
                ('num_heteroatoms', models.IntegerField()),
                ('num_valence_electrons', models.IntegerField()),
                ('num_spiro_atoms', models.IntegerField()),
                ('fraction_csp3', models.FloatField()),
                ('fp_density_morgan1', models.FloatField()),
                ('exact_mol_wt', models.FloatField()),
                ('chi0', models.FloatField()),
                ('ch1', models.FloatField()),
                ('ipc', models.FloatField()),
                ('bertz_ct', models.FloatField()),
                ('labute_asa', models.FloatField()),
                ('ic50', models.FloatField()),
            ],
        ),
    ]
