# Generated by Django 3.2 on 2021-05-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('IC50_calc', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='IC50_calc/img/mol/'),
        ),
    ]
