# Generated by Django 3.2 on 2021-05-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('IC50_calc', '0007_alter_chemistry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
